---
- name: Get os_version from /etc/os-release
  when: ansible_os_family is not defined
  raw: "grep '^VERSION_ID=' /etc/os-release | sed s'/VERSION_ID=//'"
  register: os_version
  changed_when: False
  tags:
    - os_init

- name: Get distro name from /etc/os-release
  when: ansible_os_family is not defined
  raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro
  changed_when: False
  tags:
    - os_init

- name: Set fact ansible_os_family var to Debian
  when:
    - ansible_os_family is not defined
    - "'Debian' in distro.stdout"
  set_fact:
    ansible_os_family: Debian
  tags:
    - os_init
- name: Set fact ansible_os_family var to Debian
  when:
    - ansible_os_family is not defined
    - "'Ubuntu' in distro.stdout"
  set_fact:
    ansible_os_family: Debian
  tags:
    - os_init
- name: Set fact ansible_os_family var to RedHat
  when:
    - ansible_os_family is not defined
    - "'CentOS' in distro.stdout"
  set_fact:
    ansible_os_family: RedHat
  tags:
    - os_init
- name: Override config file directory for Debian
  when: ansible_os_family == "Debian"
  set_fact:
    system_env_dir: "/etc/default"
  tags:
    - os_init

- name: Set os parameters
  include_tasks: pkg.yml

- name: rm yum repo
  shell: |
    rm  -rf  /etc/yum.repos.d/*
- name: yum repo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    trim_blocks: no
  with_items:
  - { src: "CentOS-Base.repo", dest: "/etc/yum.repos.d/CentOS-Base.repo" }
  - { src: "CentOS-Debuginfo.repo", dest: "/etc/yum.repos.d/CentOS-Debuginfo.repo" }
  - { src: "CentOS-Media.repo", dest: "/etc/yum.repos.d/CentOS-Media.repo" }
  - { src: "CentOS-Vault.repo", dest: "/etc/yum.repos.d/CentOS-Vault.repo" }
  - { src: "CentOS-CR.repo", dest: "/etc/yum.repos.d/CentOS-CR.repo" }
  - { src: "CentOS-fasttrack.repo", dest: "/etc/yum.repos.d/CentOS-fasttrack.repo" }
  - { src: "CentOS-Sources.repo", dest: "/etc/yum.repos.d/CentOS-Sources.repo" }
  - { src: "CentOS-x86_64-kernel.repo", dest: "/etc/yum.repos.d/CentOS-x86_64-kernel.repo" }
- name: make cache
  shell: |
    yum makecache

- name: Install python3
  shell: |
    yum install -y python3
- name: Install ntp
  shell: |
    yum install -y ntp ntpdate && systemctl  enable ntpd && systemctl  start ntpd